<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-1MU00UN" failures="1" tests="5" name="com.agile.testNgTutorial.sauceDemoFunction" time="15.621" errors="0" timestamp="2023-07-04T12:58:37 EDT" skipped="0">
  <testcase classname="com.agile.testNgTutorial.sauceDemoFunction" name="login" time="0.862"/>
  <system-out/>
  <testcase classname="com.agile.testNgTutorial.sauceDemoFunction" name="dashBoard" time="0.056"/>
  <system-out/>
  <testcase classname="com.agile.testNgTutorial.sauceDemoFunction" name="productAlpabeticsort" time="3.309"/>
  <system-out/>
  <testcase classname="com.agile.testNgTutorial.sauceDemoFunction" name="productPriceSort" time="3.198"/>
  <system-out/>
  <testcase classname="com.agile.testNgTutorial.sauceDemoFunction" name="pageValidation" time="8.196">
    <failure message="The following asserts failed:
	expected [https://saucelabs.com/x] but found [https://saucelabs.com/]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [https://saucelabs.com/x] but found [https://saucelabs.com/]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at com.agile.testNgTutorial.sauceDemoFunction.pageValidation(sauceDemoFunction.java:80)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- pageValidation -->
  <system-out/>
</testsuite> <!-- com.agile.testNgTutorial.sauceDemoFunction -->
